spring.application.name=airport
spring.datasource.url=jdbc:postgresql://localhost:5432/airport
spring.datasource.username=postgres
spring.datasource.password=nestea
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# дополнительное логирование к отдельным классам
#система контроля версий базы данных  flyway or liquidbase